name = "iptv-subscription-api"
main = "worker.js"
compatibility_date = "2023-05-18"

[[d1_databases]]
binding = "DB"
database_name = "iptv-subscriptions-db"
database_id = "d83ba146-78a1-48c4-a18f-28a87e81a5c6"
