org.gradle.jvmargs=-Xmx2548M -XX:MaxMetaspaceSize=512m -XX:+UseG1GC
android.useAndroidX=true
android.enableJetifier=true
flutter.versionCode=255
flutter.versionName=2.5.5
expectedCertificateSha256=80:07:86:FB:C6:AF:3F:59:EB:E2:6E:0E:53:23:5E:29:43:4B:E8:6C:06:AD:E7:1B:E4:D5:A8:11:85:07:55:10
# Work around JDK 21 image transform failures with Android SDK 35 in Gradle 8.5.
android.disableJdkImageTransform=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
