org.gradle.jvmargs=-Xmx2548M -XX:MaxMetaspaceSize=512m -XX:+UseG1GC
android.useAndroidX=true
android.enableJetifier=true
flutter.versionCode=261
flutter.versionName=2.2.61
expectedCertificateSha256=UNSET
# Work around JDK 21 image transform failures with Android SDK 35 in Gradle 8.5.
android.disableJdkImageTransform=true
