name: Build Android APK
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        run: |
          flutter build apk --debug
          mv build/app/outputs/flutter-apk/app-debug.apk LIVE_STREAM_PREMIUM_V2.2.18.apk

      - name: Create GitHub Release
        run: |
          gh release delete v2.2.18-stable --yes || true
          gh release create v2.2.18-stable LIVE_STREAM_PREMIUM_V2.2.18.apk --title "LIVE STREAM PREMIUM v2.2.18" --notes "النسخة النهائية والمستقرة v2.2.18. تم تفعيل الحماية والسماح بتصوير الشاشة."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
